zuul:
  routes:
    clientOne:
      path: /sharMainTeams/**
      service-id: sharMainTeams
  host:
    connect-timeout-millis: 15000 #HTTP连接超时要比Hystrix的大
    socket-timeout-millis: 60000   #socket超时
    
