zuul:
  routes:
    sharMainTeams:
      path: api/sharMainTeams/**
      service-id: share-main-teams
  host:
    connect-timeout-millis: 15000 #HTTP连接超时要比Hystrix的大
    socket-timeout-millis: 60000   #socket超时
    
